install:
  - set PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%
  - appveyor DownloadFile "https://raw.githubusercontent.com/swig/cccl/master/cccl"
  - appveyor DownloadFile "https://raw.githubusercontent.com/pandawing/generator-nm5/master/Execute-With-Retry.ps1"
  - call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%
  - ps: . .\Execute-With-Retry
  - ps: Execute-With-Retry { bash -c "pacman -Syu --noconfirm" }
  - ps: Execute-With-Retry { bash -c "pacman -S --noconfirm autoconf automake libtool gtk-doc mingw-w64-x86_64-pkg-config mingw-w64-x86_64-harfbuzz mingw-w64-x86_64-fribidi" }

build_script:
  - set CC=./cccl
  - set CXX=./cccl
  - bash -c "./autogen.sh"
  - bash -c "./configure"
  - bash -c "make"

#test_script:
#  - bash -c "make check"

# disable automatic tests
test: off
